Repository S-Project-Jin-Han/Q-On, pull requests merged in 2025-08, with the labels that each got.

#5 #2 [feat] 자동 배포 테스트
  .github/workflows/git-push.yml
  build.sh
Labels: Config 설정/배포

#7 #1 [Docs] 첫 기획안 리드미 작성
  README.md
Labels: 문서화 Docs

#33 [Chore/#32] PR/ISSUE 템플릿 개선
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/implementation.md
  .github/ISSUE_TEMPLATE/other.md
  .github/ISSUE_TEMPLATE/refactoring.md
  .github/pull_request_template.md
Labels: 기타 Chore, 문서화 Docs

#35 [FEAT/#34] Button 컴포넌트 구현 및 global.css 수정 / 공통 컴포넌트 의존성 추가
  .storybook/preview.ts
  components.json
  package-lock.json
  package.json
  src/app/(pages)/(public)/login/page.tsx
  src/shared/auth/components/KakaoLoginButton.tsx
  src/shared/lib/index.ts
  src/shared/styles/globals.css
  src/shared/ui/Badge/Badge.tsx
  src/shared/ui/Badge/index.ts
  src/shared/ui/Button/Button.stories.tsx
  src/shared/ui/Button/Button.tsx
  src/shared/ui/Button/Button.types.ts
  src/shared/ui/Button/buttonVariants.tsx
  src/shared/ui/Button/index.ts
  src/shared/ui/Pagination/Pagination.tsx
  src/shared/ui/Pagination/index.ts
  src/shared/ui/ScrollArea/ScrollArea.tsx
  src/shared/ui/ScrollArea/index.ts
  src/shared/ui/Skeleton/Skeleton.tsx
  src/shared/ui/Skeleton/index.ts
  src/shared/ui/Sonner/Sonner.stories.tsx
  src/shared/ui/index.ts
Labels: Config 설정/배포, 기능 구현 Feat

#39 [Feat/#31] Zustand Store 방식으로 user Client 전역 관리 리펙토링 및 SignOut 로직 구현
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/implementation.md
  .github/ISSUE_TEMPLATE/other.md
  .github/ISSUE_TEMPLATE/refactoring.md
  src/app/(pages)/page.tsx
  src/app/api/auth/callback/route.ts
  src/app/api/auth/session/route.ts
  src/app/api/auth/signout/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/middleware.ts
  src/shared/auth/AuthHydrator.tsx
  src/shared/auth/components/SignOutButton.tsx
  src/shared/auth/components/UserInfo.tsx
  src/shared/auth/components/index.ts
  src/shared/auth/getUserWithProfile.ts
  src/shared/auth/types/auth.types.ts
  src/shared/auth/types/index.ts
  src/shared/auth/types/profile.types.ts
  src/shared/auth/types/role.types.ts
  src/shared/auth/types/sessionUser.ts
  src/shared/auth/types/user.types.ts
  src/shared/lib/env/env.client.ts
  src/shared/lib/env/env.server.ts
  src/shared/lib/supabase/supabase-browser.ts
  src/shared/lib/supabase/supabase-server.ts
  src/shared/provider/UserProvider.tsx
  src/shared/store/authStore.ts
  src/shared/store/useExampleStore.ts
Labels: 기능 구현 Feat

#38 [FEAT/#37] Icon 컴포넌트 구현
  src/shared/styles/globals.css
  src/shared/ui/Icon/CustomIcon.tsx
  src/shared/ui/Icon/CustomTypes.ts
  src/shared/ui/Icon/Icon.stories.tsx
  src/shared/ui/Icon/Icon.tsx
  src/shared/ui/Icon/Icon.types.ts
  src/shared/ui/Icon/LucideIcon.tsx
  src/shared/ui/Icon/LucideTypes.ts
  src/shared/ui/Icon/iconVariants.tsx
  src/shared/ui/Icon/index.ts
  src/shared/ui/index.ts
Labels: 기능 구현 Feat
